FROM amazonlinux as builder
RUN yum update && yum install -y java-11-amazon-corretto-devel.x86_64 && yum install maven -y 
COPY ./fdec-student-ui/ /mnt/fdec-student-ui/.
WORKDIR /mnt/fdec-student-ui
RUN mvn package

FROM tomcat 
COPY --from=builder /mnt/fdec-student-ui/target/*.war webapps/.
